In [41]:
import numpy as np

In [42]:
def train(inputs, bottom_up_weights, top_down_weights, rho, lr, n):
    print("bottom up weights: ", bottom_up_weights)
    print("top down weights: ", top_down_weights)

    for s in inputs:
        print("Input pattern: ", s)
        norm_s = np.sum(s)
        print("||s|| : ", norm_s)

        y = np.dot(s, bottom_up_weights)
        print("Output of network(y) = bij*xi = ", y)

        J=winner(y)
        print("Winner neuron: ", J)

        xi = s * top_down_weights[J]
        print("Input weights for adjustment: ", xi)
        
        norm_x = np.sum(xi)
        print("Norm of Weight: ", norm_x)
        
        test_rest = norm_x / norm_s
        print("Ratio: ", test_rest)
        print("Threshold(rho): ", rho)

        if test_rest>=rho:
            print("Reset triggred.")
            for i in range(n):
                bottom_up_weights[i][J] = lr*xi[i]/(lr-1+norm_x)
                top_down_weights[J][i] = xi[i]
            print("Updated bottom_up_weights: ", bottom_up_weights)
            print("Updated top_down_weights: ", top_down_weights)

        else:
            print("Reset not triggred.")

In [43]:
def winner(y):
    return np.argmax(y)

In [44]:
inputs = np.array([[0,0,0,1], [0,1,0,1], [0,0,1,1], [1,0,0,0]])
lr = 2
rho = 0.4
n=4
m=3

In [45]:
initial_bottom_up_weights = 1/(1+n)
bottom_up_weights = np.full((n, m), initial_bottom_up_weights)
top_down_weights = np.full((m,n ), 1)

In [46]:
train(inputs, bottom_up_weights, top_down_weights, rho, lr, n)

bottom up weights:  [[0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]]
top down weights:  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Input pattern:  [0 0 0 1]
||s|| :  1
Output of network(y) = bij*xi =  [0.2 0.2 0.2]
Winner neuron:  0
Input weights for adjustment:  [0 0 0 1]
Norm of Weight:  1
Ratio:  1.0
Threshold(rho):  0.4
Reset triggred.
Updated bottom_up_weights:  [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]]
Updated top_down_weights:  [[0 0 0 1]
 [1 1 1 1]
 [1 1 1 1]]
Input pattern:  [0 1 0 1]
||s|| :  2
Output of network(y) = bij*xi =  [1.  0.4 0.4]
Winner neuron:  0
Input weights for adjustment:  [0 0 0 1]
Norm of Weight:  1
Ratio:  0.5
Threshold(rho):  0.4
Reset triggred.
Updated bottom_up_weights:  [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]]
Updated top_down_weights:  [[0 0 0 1]
 [1 1 1 1]
 [1 1 1 1]]
Input pattern:  [0 0 1 1]
||s|| :  2
Output of network(y) = bij*xi =  [1.  0.4 0.4]
Winner neuron:  0
Input weights for adjustment:  [0 0 0 1]
N