In [1]:
import numpy as np

In [2]:
class Hopfield:
    def __init__(self, num_neurons):
        self.num_neurons = num_neurons
        self.weights = np.zeros((num_neurons, num_neurons))
    
    def sigmoid(self, x):
        return (1-np.exp(-x))/(1+np.exp(-x))

    def train(self, vectors):
        for vector in vectors:
            vector = np.reshape(vector, (self.num_neurons, 1))
            self.weights += np.dot(vector, vector.T)
        print("Weights: \n", self.weights)

    def recall(self, input_vector):
        output = np.dot(input_vector, self.weights)
        output = self.sigmoid(output)
        output = np.sign(output)
        return output

In [3]:
network = Hopfield(8)

In [5]:
vectors = np.array([[-1,-1,-1,-1,1,1,1,1],
                   [1,1,1,1,-1,-1,-1,-1],
                   [1,-1,1,-1,1,1,-1,1],
                   [-1,1,-1,1,-1,-1,1,-1]])
network.train(vectors)

vector = np.array([[-1,-1,-1,-1,1,0,1,0],
                    [0,1,1,1,-1,-1,-1,-1],
                    [1,-1,0,-1,1,1,-1,1],
                    [0,1,-1,1,-1,0,1,-1]])
for vect in vector:
    output = network.recall(vect)
    print("\nInput: ", vect)
    print("Output: ", output)

Weights: 
 [[ 8.  0.  8.  0.  0.  0. -8.  0.]
 [ 0.  8.  0.  8. -8. -8.  0. -8.]
 [ 8.  0.  8.  0.  0.  0. -8.  0.]
 [ 0.  8.  0.  8. -8. -8.  0. -8.]
 [ 0. -8.  0. -8.  8.  8.  0.  8.]
 [ 0. -8.  0. -8.  8.  8.  0.  8.]
 [-8.  0. -8.  0.  0.  0.  8.  0.]
 [ 0. -8.  0. -8.  8.  8.  0.  8.]]

Input:  [-1 -1 -1 -1  1  0  1  0]
Output:  [-1. -1. -1. -1.  1.  1.  1.  1.]

Input:  [ 0  1  1  1 -1 -1 -1 -1]
Output:  [ 1.  1.  1.  1. -1. -1. -1. -1.]

Input:  [ 1 -1  0 -1  1  1 -1  1]
Output:  [ 1. -1.  1. -1.  1.  1. -1.  1.]

Input:  [ 0  1 -1  1 -1  0  1 -1]
Output:  [-1.  1. -1.  1. -1. -1.  1. -1.]


In [11]:
class Hopfield:
    def __init__(self, num_neurons):
        self.num_neurons = num_neurons
        self.weights = np.zeros((num_neurons, num_neurons))

    def sigmoid(self, x):
        return (1-np.exp(-x))/(1+np.exp(-x))

    def train(self, vectors):
        num_vectors = len(vectors)
        for vector in vectors:
            vector = np.reshape(vector, (self.num_neurons, 1))
            self.weights += np.dot(vector, vector.T)
        print("Weights: \n", self.weights)

    def recall(self, input_vector):
        output = np.dot(input_vector, self.weights)
        output = self.sigmoid(output)
        output = np.sign(output)
        return output

In [12]:
network = Hopfield(8)

vectors = np.array([[-1,-1,-1,-1,1,1,1,1],
                   [1,1,1,1,-1,-1,-1,-1],
                   [1,-1,1,-1,1,1,-1,1],
                   [-1,1,-1,1,-1,-1,1,-1]])

network.train(vectors)

vector = np.array([[-1,-1,-1,-1,1,0,1,0],
                    [0,1,1,1,-1,-1,-1,-1],
                    [1,-1,0,-1,1,1,-1,1],
                    [0,1,-1,1,-1,0,1,-1]])

for vect in vector:
    output = network.recall(vect)
    print("\nInput: ", vect)
    print("\nOutput: ", output)

Weights: 
 [[ 4.  0.  4.  0.  0.  0. -4.  0.]
 [ 0.  4.  0.  4. -4. -4.  0. -4.]
 [ 4.  0.  4.  0.  0.  0. -4.  0.]
 [ 0.  4.  0.  4. -4. -4.  0. -4.]
 [ 0. -4.  0. -4.  4.  4.  0.  4.]
 [ 0. -4.  0. -4.  4.  4.  0.  4.]
 [-4.  0. -4.  0.  0.  0.  4.  0.]
 [ 0. -4.  0. -4.  4.  4.  0.  4.]]

Input:  [-1 -1 -1 -1  1  0  1  0]

Output:  [-1. -1. -1. -1.  1.  1.  1.  1.]

Input:  [ 0  1  1  1 -1 -1 -1 -1]

Output:  [ 1.  1.  1.  1. -1. -1. -1. -1.]

Input:  [ 1 -1  0 -1  1  1 -1  1]

Output:  [ 1. -1.  1. -1.  1.  1. -1.  1.]

Input:  [ 0  1 -1  1 -1  0  1 -1]

Output:  [-1.  1. -1.  1. -1. -1.  1. -1.]
